var annotated_dup =
[
    [ "VerticesEngine", "namespace_vertices_engine.html", [
      [ "Audio", "namespace_vertices_engine_1_1_audio.html", [
        [ "Exceptions", "namespace_vertices_engine_1_1_audio_1_1_exceptions.html", [
          [ "vxSoundEffectException", "class_vertices_engine_1_1_audio_1_1_exceptions_1_1vx_sound_effect_exception.html", null ]
        ] ],
        [ "vxAudioManager", "class_vertices_engine_1_1_audio_1_1vx_audio_manager.html", "class_vertices_engine_1_1_audio_1_1vx_audio_manager" ],
        [ "vxSong", "class_vertices_engine_1_1_audio_1_1vx_song.html", null ],
        [ "vxSoundEffectInfo", "struct_vertices_engine_1_1_audio_1_1vx_sound_effect_info.html", null ],
        [ "vxSoundEffectManager", "class_vertices_engine_1_1_audio_1_1vx_sound_effect_manager.html", "class_vertices_engine_1_1_audio_1_1vx_sound_effect_manager" ]
      ] ],
      [ "Commands", "namespace_vertices_engine_1_1_commands.html", [
        [ "vxCMDAddSandbox3DItem", "class_vertices_engine_1_1_commands_1_1vx_c_m_d_add_sandbox3_d_item.html", "class_vertices_engine_1_1_commands_1_1vx_c_m_d_add_sandbox3_d_item" ],
        [ "vxCMDBaseSandbox3DCommand", "class_vertices_engine_1_1_commands_1_1vx_c_m_d_base_sandbox3_d_command.html", "class_vertices_engine_1_1_commands_1_1vx_c_m_d_base_sandbox3_d_command" ],
        [ "vxCMDDeleteSandbox3DItem", "class_vertices_engine_1_1_commands_1_1vx_c_m_d_delete_sandbox3_d_item.html", "class_vertices_engine_1_1_commands_1_1vx_c_m_d_delete_sandbox3_d_item" ],
        [ "vxCMDEntityInfo", "class_vertices_engine_1_1_commands_1_1vx_c_m_d_entity_info.html", null ],
        [ "vxCMDTransformChanged", "class_vertices_engine_1_1_commands_1_1vx_c_m_d_transform_changed.html", "class_vertices_engine_1_1_commands_1_1vx_c_m_d_transform_changed" ],
        [ "vxCMDTranslateSandbox3DItem", "class_vertices_engine_1_1_commands_1_1vx_c_m_d_translate_sandbox3_d_item.html", "class_vertices_engine_1_1_commands_1_1vx_c_m_d_translate_sandbox3_d_item" ],
        [ "vxCommand", "class_vertices_engine_1_1_commands_1_1vx_command.html", "class_vertices_engine_1_1_commands_1_1vx_command" ],
        [ "vxCommandManager", "class_vertices_engine_1_1_commands_1_1vx_command_manager.html", "class_vertices_engine_1_1_commands_1_1vx_command_manager" ]
      ] ],
      [ "ContentManagement", "namespace_vertices_engine_1_1_content_management.html", [
        [ "LevelContentEntry", "struct_vertices_engine_1_1_content_management_1_1_level_content_entry.html", null ],
        [ "TextAsset", "class_vertices_engine_1_1_content_management_1_1_text_asset.html", null ],
        [ "TextAssetReader", "class_vertices_engine_1_1_content_management_1_1_text_asset_reader.html", null ],
        [ "vxContentManager", "class_vertices_engine_1_1_content_management_1_1vx_content_manager.html", "class_vertices_engine_1_1_content_management_1_1vx_content_manager" ],
        [ "vxInternalContentManager", "class_vertices_engine_1_1_content_management_1_1vx_internal_content_manager.html", "class_vertices_engine_1_1_content_management_1_1vx_internal_content_manager" ],
        [ "vxLevelContentManager", "class_vertices_engine_1_1_content_management_1_1vx_level_content_manager.html", "class_vertices_engine_1_1_content_management_1_1vx_level_content_manager" ]
      ] ],
      [ "Controllers", "namespace_vertices_engine_1_1_controllers.html", [
        [ "CameraControlScheme", "class_vertices_engine_1_1_controllers_1_1_camera_control_scheme.html", "class_vertices_engine_1_1_controllers_1_1_camera_control_scheme" ],
        [ "CharacterCameraControlScheme", "class_vertices_engine_1_1_controllers_1_1_character_camera_control_scheme.html", "class_vertices_engine_1_1_controllers_1_1_character_camera_control_scheme" ],
        [ "CharacterControllerInput", "class_vertices_engine_1_1_controllers_1_1_character_controller_input.html", "class_vertices_engine_1_1_controllers_1_1_character_controller_input" ]
      ] ],
      [ "Core", "namespace_vertices_engine_1_1_core.html", [
        [ "Android", "namespace_vertices_engine_1_1_core_1_1_android.html", [
          [ "Class1", "class_vertices_engine_1_1_core_1_1_android_1_1_class1.html", null ]
        ] ]
      ] ],
      [ "DebugUtilities", "namespace_vertices_engine_1_1_debug_utilities.html", [
        [ "PrimitiveBatch", "class_vertices_engine_1_1_debug_utilities_1_1_primitive_batch.html", "class_vertices_engine_1_1_debug_utilities_1_1_primitive_batch" ],
        [ "vxFarseerDebugView", "class_vertices_engine_1_1_debug_utilities_1_1vx_farseer_debug_view.html", null ]
      ] ],
      [ "Diagnostics", "namespace_vertices_engine_1_1_diagnostics.html", [
        [ "CommandInfo", "class_vertices_engine_1_1_diagnostics_1_1_command_info.html", null ],
        [ "IDebugCommandExecutioner", "interface_vertices_engine_1_1_diagnostics_1_1_i_debug_command_executioner.html", "interface_vertices_engine_1_1_diagnostics_1_1_i_debug_command_executioner" ],
        [ "IDebugCommandHost", "interface_vertices_engine_1_1_diagnostics_1_1_i_debug_command_host.html", "interface_vertices_engine_1_1_diagnostics_1_1_i_debug_command_host" ],
        [ "IDebugEchoListner", "interface_vertices_engine_1_1_diagnostics_1_1_i_debug_echo_listner.html", "interface_vertices_engine_1_1_diagnostics_1_1_i_debug_echo_listner" ],
        [ "KeyboardUtils", "class_vertices_engine_1_1_diagnostics_1_1_keyboard_utils.html", "class_vertices_engine_1_1_diagnostics_1_1_keyboard_utils" ],
        [ "StringBuilderExtensions", "class_vertices_engine_1_1_diagnostics_1_1_string_builder_extensions.html", "class_vertices_engine_1_1_diagnostics_1_1_string_builder_extensions" ],
        [ "vxCrashHandler", "class_vertices_engine_1_1_diagnostics_1_1vx_crash_handler.html", "class_vertices_engine_1_1_diagnostics_1_1vx_crash_handler" ],
        [ "vxDebugCommandUI", "class_vertices_engine_1_1_diagnostics_1_1vx_debug_command_u_i.html", "class_vertices_engine_1_1_diagnostics_1_1vx_debug_command_u_i" ],
        [ "vxDebugControlAttribute", "class_vertices_engine_1_1_diagnostics_1_1vx_debug_control_attribute.html", null ],
        [ "vxDebugMethodAttribute", "class_vertices_engine_1_1_diagnostics_1_1vx_debug_method_attribute.html", null ],
        [ "vxDebugText", "class_vertices_engine_1_1_diagnostics_1_1vx_debug_text.html", null ],
        [ "vxDebugTimerGraphSet", "class_vertices_engine_1_1_diagnostics_1_1vx_debug_timer_graph_set.html", "class_vertices_engine_1_1_diagnostics_1_1vx_debug_timer_graph_set" ],
        [ "vxDebugUIControlBaseClass", "class_vertices_engine_1_1_diagnostics_1_1vx_debug_u_i_control_base_class.html", "class_vertices_engine_1_1_diagnostics_1_1vx_debug_u_i_control_base_class" ],
        [ "vxFpsCounterDebugControl", "class_vertices_engine_1_1_diagnostics_1_1vx_fps_counter_debug_control.html", "class_vertices_engine_1_1_diagnostics_1_1vx_fps_counter_debug_control" ],
        [ "vxProfiler", "class_vertices_engine_1_1_diagnostics_1_1vx_profiler.html", "class_vertices_engine_1_1_diagnostics_1_1vx_profiler" ],
        [ "vxProfilerGraphDebugControl", "class_vertices_engine_1_1_diagnostics_1_1vx_profiler_graph_debug_control.html", "class_vertices_engine_1_1_diagnostics_1_1vx_profiler_graph_debug_control" ],
        [ "vxSandboxCommandDebugControl", "class_vertices_engine_1_1_diagnostics_1_1vx_sandbox_command_debug_control.html", "class_vertices_engine_1_1_diagnostics_1_1vx_sandbox_command_debug_control" ],
        [ "vxScreenConsoleDebugControl", "class_vertices_engine_1_1_diagnostics_1_1vx_screen_console_debug_control.html", "class_vertices_engine_1_1_diagnostics_1_1vx_screen_console_debug_control" ],
        [ "vxSpriteBatchCountDebugControl", "class_vertices_engine_1_1_diagnostics_1_1vx_sprite_batch_count_debug_control.html", "class_vertices_engine_1_1_diagnostics_1_1vx_sprite_batch_count_debug_control" ],
        [ "vxSystemProfiler", "class_vertices_engine_1_1_diagnostics_1_1vx_system_profiler.html", "class_vertices_engine_1_1_diagnostics_1_1vx_system_profiler" ],
        [ "vxTimeRulerDebugControl", "class_vertices_engine_1_1_diagnostics_1_1vx_time_ruler_debug_control.html", "class_vertices_engine_1_1_diagnostics_1_1vx_time_ruler_debug_control" ]
      ] ],
      [ "Droid", "namespace_vertices_engine_1_1_droid.html", [
        [ "Resource", "class_vertices_engine_1_1_droid_1_1_resource.html", "class_vertices_engine_1_1_droid_1_1_resource" ]
      ] ],
      [ "DX", "namespace_vertices_engine_1_1_d_x.html", [
        [ "Game1", "class_vertices_engine_1_1_d_x_1_1_game1.html", null ],
        [ "Program", "class_vertices_engine_1_1_d_x_1_1_program.html", null ]
      ] ],
      [ "Editor", "namespace_vertices_engine_1_1_editor.html", [
        [ "Entities", "namespace_vertices_engine_1_1_editor_1_1_entities.html", [
          [ "vxBoundingVolume", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_bounding_volume.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_bounding_volume" ],
          [ "vxEditorEntity", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_editor_entity.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_editor_entity" ],
          [ "vxEditorEntityMaterial", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_editor_entity_material.html", null ],
          [ "vxGizmo", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo" ],
          [ "vxGizmoAxisRotationEntity", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo_axis_rotation_entity.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo_axis_rotation_entity" ],
          [ "vxGizmoAxisTranslationEntity", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo_axis_translation_entity.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo_axis_translation_entity" ],
          [ "vxGizmoHotKeyTranslationEntity", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo_hot_key_translation_entity.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo_hot_key_translation_entity" ],
          [ "vxGizmoPanTranslationEntity", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo_pan_translation_entity.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo_pan_translation_entity" ],
          [ "vxGizmoTransformationBaseEntity", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo_transformation_base_entity.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_gizmo_transformation_base_entity" ],
          [ "vxResizingGizmoHandle", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_resizing_gizmo_handle.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_resizing_gizmo_handle" ],
          [ "vxScaleBar", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_scale_bar.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_scale_bar" ],
          [ "vxScaleCube", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_scale_cube.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_scale_cube" ],
          [ "vxWorkingPlane", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_working_plane.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1vx_working_plane" ],
          [ "WorkingPlaneRenderer", "class_vertices_engine_1_1_editor_1_1_entities_1_1_working_plane_renderer.html", "class_vertices_engine_1_1_editor_1_1_entities_1_1_working_plane_renderer" ]
        ] ],
        [ "UI", "namespace_vertices_engine_1_1_editor_1_1_u_i.html", [
          [ "vxSelectionBox", "class_vertices_engine_1_1_editor_1_1_u_i_1_1vx_selection_box.html", "class_vertices_engine_1_1_editor_1_1_u_i_1_1vx_selection_box" ]
        ] ]
      ] ],
      [ "Entities", "namespace_vertices_engine_1_1_entities.html", [
        [ "Terrain", "namespace_vertices_engine_1_1_entities_1_1_terrain.html", [
          [ "vxTerrainRenderer", "class_vertices_engine_1_1_entities_1_1_terrain_1_1vx_terrain_renderer.html", "class_vertices_engine_1_1_entities_1_1_terrain_1_1vx_terrain_renderer" ]
        ] ],
        [ "vxCharacter3DBaseClass", "class_vertices_engine_1_1_entities_1_1vx_character3_d_base_class.html", null ],
        [ "vxImportedEntity3D", "class_vertices_engine_1_1_entities_1_1vx_imported_entity3_d.html", "class_vertices_engine_1_1_entities_1_1vx_imported_entity3_d" ],
        [ "vxObjectPool", "class_vertices_engine_1_1_entities_1_1vx_object_pool.html", "class_vertices_engine_1_1_entities_1_1vx_object_pool" ],
        [ "vxRegisterObjectPoolAttribute", "class_vertices_engine_1_1_entities_1_1vx_register_object_pool_attribute.html", "class_vertices_engine_1_1_entities_1_1vx_register_object_pool_attribute" ],
        [ "vxSkyBox", "class_vertices_engine_1_1_entities_1_1vx_sky_box.html", "class_vertices_engine_1_1_entities_1_1vx_sky_box" ],
        [ "vxSunEntity", "class_vertices_engine_1_1_entities_1_1vx_sun_entity.html", "class_vertices_engine_1_1_entities_1_1vx_sun_entity" ]
      ] ],
      [ "EnvTerrain", "namespace_vertices_engine_1_1_env_terrain.html", [
        [ "vxTerrainChunk", "class_vertices_engine_1_1_env_terrain_1_1vx_terrain_chunk.html", "class_vertices_engine_1_1_env_terrain_1_1vx_terrain_chunk" ],
        [ "vxTerrainManager", "class_vertices_engine_1_1_env_terrain_1_1vx_terrain_manager.html", "class_vertices_engine_1_1_env_terrain_1_1vx_terrain_manager" ],
        [ "vxTerrainMaterial", "class_vertices_engine_1_1_env_terrain_1_1vx_terrain_material.html", null ]
      ] ],
      [ "Graphics", "namespace_vertices_engine_1_1_graphics.html", [
        [ "Animation", "namespace_vertices_engine_1_1_graphics_1_1_animation.html", [
          [ "vxAnimationSprite2D", "class_vertices_engine_1_1_graphics_1_1_animation_1_1vx_animation_sprite2_d.html", "class_vertices_engine_1_1_graphics_1_1_animation_1_1vx_animation_sprite2_d" ]
        ] ],
        [ "Rendering", "namespace_vertices_engine_1_1_graphics_1_1_rendering.html", [
          [ "vxStaticMeshBatchEntity", "class_vertices_engine_1_1_graphics_1_1_rendering_1_1vx_static_mesh_batch_entity.html", "class_vertices_engine_1_1_graphics_1_1_rendering_1_1vx_static_mesh_batch_entity" ],
          [ "vxStaticMeshBatchRenderer", "class_vertices_engine_1_1_graphics_1_1_rendering_1_1vx_static_mesh_batch_renderer.html", "class_vertices_engine_1_1_graphics_1_1_rendering_1_1vx_static_mesh_batch_renderer" ]
        ] ],
        [ "Layer", "class_vertices_engine_1_1_graphics_1_1_layer.html", null ],
        [ "LensFlareComponent", "class_vertices_engine_1_1_graphics_1_1_lens_flare_component.html", "class_vertices_engine_1_1_graphics_1_1_lens_flare_component" ],
        [ "NonPhotoRealisticSettings", "class_vertices_engine_1_1_graphics_1_1_non_photo_realistic_settings.html", "class_vertices_engine_1_1_graphics_1_1_non_photo_realistic_settings" ],
        [ "TextureSet", "class_vertices_engine_1_1_graphics_1_1_texture_set.html", null ],
        [ "vxAntiAliasPostProcess", "class_vertices_engine_1_1_graphics_1_1vx_anti_alias_post_process.html", "class_vertices_engine_1_1_graphics_1_1vx_anti_alias_post_process" ],
        [ "vxAssetCreator2D", "class_vertices_engine_1_1_graphics_1_1vx_asset_creator2_d.html", null ],
        [ "vxBlurEffectsPostProcess", "class_vertices_engine_1_1_graphics_1_1vx_blur_effects_post_process.html", "class_vertices_engine_1_1_graphics_1_1vx_blur_effects_post_process" ],
        [ "vxCameraMotionBlurPostProcess", "class_vertices_engine_1_1_graphics_1_1vx_camera_motion_blur_post_process.html", "class_vertices_engine_1_1_graphics_1_1vx_camera_motion_blur_post_process" ],
        [ "vxCascadeShadowRenderPass", "class_vertices_engine_1_1_graphics_1_1vx_cascade_shadow_render_pass.html", "class_vertices_engine_1_1_graphics_1_1vx_cascade_shadow_render_pass" ],
        [ "vxDebugEffect", "class_vertices_engine_1_1_graphics_1_1vx_debug_effect.html", "class_vertices_engine_1_1_graphics_1_1vx_debug_effect" ],
        [ "vxDebugRenderPass", "class_vertices_engine_1_1_graphics_1_1vx_debug_render_pass.html", "class_vertices_engine_1_1_graphics_1_1vx_debug_render_pass" ],
        [ "vxDirectionalLight", "class_vertices_engine_1_1_graphics_1_1vx_directional_light.html", "class_vertices_engine_1_1_graphics_1_1vx_directional_light" ],
        [ "vxDistortionPostProcess", "class_vertices_engine_1_1_graphics_1_1vx_distortion_post_process.html", "class_vertices_engine_1_1_graphics_1_1vx_distortion_post_process" ],
        [ "vxDistortionPostProcess2D", "class_vertices_engine_1_1_graphics_1_1vx_distortion_post_process2_d.html", "class_vertices_engine_1_1_graphics_1_1vx_distortion_post_process2_d" ],
        [ "vxEdgeDetectPostProcess", "class_vertices_engine_1_1_graphics_1_1vx_edge_detect_post_process.html", "class_vertices_engine_1_1_graphics_1_1vx_edge_detect_post_process" ],
        [ "vxEditorTempEntityEffect", "class_vertices_engine_1_1_graphics_1_1vx_editor_temp_entity_effect.html", "class_vertices_engine_1_1_graphics_1_1vx_editor_temp_entity_effect" ],
        [ "vxEffectParameter", "class_vertices_engine_1_1_graphics_1_1vx_effect_parameter.html", "class_vertices_engine_1_1_graphics_1_1vx_effect_parameter" ],
        [ "vxEntityRenderer", "class_vertices_engine_1_1_graphics_1_1vx_entity_renderer.html", "class_vertices_engine_1_1_graphics_1_1vx_entity_renderer" ],
        [ "vxFogPostProcess", "class_vertices_engine_1_1_graphics_1_1vx_fog_post_process.html", "class_vertices_engine_1_1_graphics_1_1vx_fog_post_process" ],
        [ "vxGBufferRenderingPass", "class_vertices_engine_1_1_graphics_1_1vx_g_buffer_rendering_pass.html", "class_vertices_engine_1_1_graphics_1_1vx_g_buffer_rendering_pass" ],
        [ "vxGraphics", "class_vertices_engine_1_1_graphics_1_1vx_graphics.html", "class_vertices_engine_1_1_graphics_1_1vx_graphics" ],
        [ "vxImportResult", "class_vertices_engine_1_1_graphics_1_1vx_import_result.html", null ],
        [ "vxIRenderPass", "interface_vertices_engine_1_1_graphics_1_1vx_i_render_pass.html", null ],
        [ "vxLensFlareComponent", "class_vertices_engine_1_1_graphics_1_1vx_lens_flare_component.html", "class_vertices_engine_1_1_graphics_1_1vx_lens_flare_component" ],
        [ "vxLightEntity", "class_vertices_engine_1_1_graphics_1_1vx_light_entity.html", "class_vertices_engine_1_1_graphics_1_1vx_light_entity" ],
        [ "vxLineBatch", "class_vertices_engine_1_1_graphics_1_1vx_line_batch.html", null ],
        [ "vxLineRenderer", "class_vertices_engine_1_1_graphics_1_1vx_line_renderer.html", "class_vertices_engine_1_1_graphics_1_1vx_line_renderer" ],
        [ "vxMainScene2DRenderPass", "class_vertices_engine_1_1_graphics_1_1vx_main_scene2_d_render_pass.html", "class_vertices_engine_1_1_graphics_1_1vx_main_scene2_d_render_pass" ],
        [ "vxMainScene3DRenderPass", "class_vertices_engine_1_1_graphics_1_1vx_main_scene3_d_render_pass.html", "class_vertices_engine_1_1_graphics_1_1vx_main_scene3_d_render_pass" ],
        [ "vxMaterial", "class_vertices_engine_1_1_graphics_1_1vx_material.html", "class_vertices_engine_1_1_graphics_1_1vx_material" ],
        [ "vxMesh", "class_vertices_engine_1_1_graphics_1_1vx_mesh.html", "class_vertices_engine_1_1_graphics_1_1vx_mesh" ],
        [ "vxMeshHelper", "class_vertices_engine_1_1_graphics_1_1vx_mesh_helper.html", "class_vertices_engine_1_1_graphics_1_1vx_mesh_helper" ],
        [ "vxMeshRenderer", "class_vertices_engine_1_1_graphics_1_1vx_mesh_renderer.html", "class_vertices_engine_1_1_graphics_1_1vx_mesh_renderer" ],
        [ "vxMeshSet", "class_vertices_engine_1_1_graphics_1_1vx_mesh_set.html", "class_vertices_engine_1_1_graphics_1_1vx_mesh_set" ],
        [ "vxMeshVertex", "struct_vertices_engine_1_1_graphics_1_1vx_mesh_vertex.html", "struct_vertices_engine_1_1_graphics_1_1vx_mesh_vertex" ],
        [ "vxModelMesh", "class_vertices_engine_1_1_graphics_1_1vx_model_mesh.html", "class_vertices_engine_1_1_graphics_1_1vx_model_mesh" ],
        [ "vxModelMeshPart", "class_vertices_engine_1_1_graphics_1_1vx_model_mesh_part.html", "class_vertices_engine_1_1_graphics_1_1vx_model_mesh_part" ],
        [ "vxModelVoxel", "class_vertices_engine_1_1_graphics_1_1vx_model_voxel.html", "class_vertices_engine_1_1_graphics_1_1vx_model_voxel" ],
        [ "vxOutlineEffect", "class_vertices_engine_1_1_graphics_1_1vx_outline_effect.html", "class_vertices_engine_1_1_graphics_1_1vx_outline_effect" ],
        [ "vxParticleRenderer", "class_vertices_engine_1_1_graphics_1_1vx_particle_renderer.html", null ],
        [ "vxRenderPass", "class_vertices_engine_1_1_graphics_1_1vx_render_pass.html", "class_vertices_engine_1_1_graphics_1_1vx_render_pass" ],
        [ "vxRenderPipeline", "class_vertices_engine_1_1_graphics_1_1vx_render_pipeline.html", "class_vertices_engine_1_1_graphics_1_1vx_render_pipeline" ],
        [ "vxRenderSettings", "class_vertices_engine_1_1_graphics_1_1vx_render_settings.html", null ],
        [ "vxSceneBlurPostProcess", "class_vertices_engine_1_1_graphics_1_1vx_scene_blur_post_process.html", "class_vertices_engine_1_1_graphics_1_1vx_scene_blur_post_process" ],
        [ "vxSceneLightRenderingPass", "class_vertices_engine_1_1_graphics_1_1vx_scene_light_rendering_pass.html", "class_vertices_engine_1_1_graphics_1_1vx_scene_light_rendering_pass" ],
        [ "vxSelectedItemEdgePostProcess", "class_vertices_engine_1_1_graphics_1_1vx_selected_item_edge_post_process.html", "class_vertices_engine_1_1_graphics_1_1vx_selected_item_edge_post_process" ],
        [ "vxShader", "class_vertices_engine_1_1_graphics_1_1vx_shader.html", null ],
        [ "vxShadowEffect", "class_vertices_engine_1_1_graphics_1_1vx_shadow_effect.html", "class_vertices_engine_1_1_graphics_1_1vx_shadow_effect" ],
        [ "vxSkyBoxMaterial", "class_vertices_engine_1_1_graphics_1_1vx_sky_box_material.html", null ],
        [ "vxSkyboxRenderer", "class_vertices_engine_1_1_graphics_1_1vx_skybox_renderer.html", null ],
        [ "vxSpriteBatch", "class_vertices_engine_1_1_graphics_1_1vx_sprite_batch.html", "class_vertices_engine_1_1_graphics_1_1vx_sprite_batch" ],
        [ "vxSpriteRenderer", "class_vertices_engine_1_1_graphics_1_1vx_sprite_renderer.html", "class_vertices_engine_1_1_graphics_1_1vx_sprite_renderer" ],
        [ "vxStaticMeshRenderer", "class_vertices_engine_1_1_graphics_1_1vx_static_mesh_renderer.html", "class_vertices_engine_1_1_graphics_1_1vx_static_mesh_renderer" ],
        [ "vxSunLightPostProcess", "class_vertices_engine_1_1_graphics_1_1vx_sun_light_post_process.html", "class_vertices_engine_1_1_graphics_1_1vx_sun_light_post_process" ],
        [ "vxTerrainMeshPart", "class_vertices_engine_1_1_graphics_1_1vx_terrain_mesh_part.html", "class_vertices_engine_1_1_graphics_1_1vx_terrain_mesh_part" ],
        [ "vxTerrainModelMesh", "class_vertices_engine_1_1_graphics_1_1vx_terrain_model_mesh.html", null ],
        [ "vxUtilityEffect", "class_vertices_engine_1_1_graphics_1_1vx_utility_effect.html", "class_vertices_engine_1_1_graphics_1_1vx_utility_effect" ],
        [ "vxViewportManager", "class_vertices_engine_1_1_graphics_1_1vx_viewport_manager.html", "class_vertices_engine_1_1_graphics_1_1vx_viewport_manager" ],
        [ "vxWaterMaterial", "class_vertices_engine_1_1_graphics_1_1vx_water_material.html", null ]
      ] ],
      [ "InitSteps", "namespace_vertices_engine_1_1_init_steps.html", [
        [ "SignInUserInitStep", "class_vertices_engine_1_1_init_steps_1_1_sign_in_user_init_step.html", "class_vertices_engine_1_1_init_steps_1_1_sign_in_user_init_step" ]
      ] ],
      [ "Input", "namespace_vertices_engine_1_1_input.html", [
        [ "Events", "namespace_vertices_engine_1_1_input_1_1_events.html", [
          [ "PlayerIndexEventArgs", "class_vertices_engine_1_1_input_1_1_events_1_1_player_index_event_args.html", "class_vertices_engine_1_1_input_1_1_events_1_1_player_index_event_args" ]
        ] ],
        [ "Accelerometer", "class_vertices_engine_1_1_input_1_1_accelerometer.html", "class_vertices_engine_1_1_input_1_1_accelerometer" ],
        [ "AccelerometerState", "struct_vertices_engine_1_1_input_1_1_accelerometer_state.html", "struct_vertices_engine_1_1_input_1_1_accelerometer_state" ],
        [ "PlayerGamePadDisconnectEventArgs", "class_vertices_engine_1_1_input_1_1_player_game_pad_disconnect_event_args.html", "class_vertices_engine_1_1_input_1_1_player_game_pad_disconnect_event_args" ],
        [ "TouchCollectionExtensions", "class_vertices_engine_1_1_input_1_1_touch_collection_extensions.html", "class_vertices_engine_1_1_input_1_1_touch_collection_extensions" ],
        [ "VirtualGamePad", "class_vertices_engine_1_1_input_1_1_virtual_game_pad.html", "class_vertices_engine_1_1_input_1_1_virtual_game_pad" ],
        [ "vxInput", "class_vertices_engine_1_1_input_1_1vx_input.html", "class_vertices_engine_1_1_input_1_1vx_input" ],
        [ "vxKeyBinding", "class_vertices_engine_1_1_input_1_1vx_key_binding.html", null ],
        [ "vxKeyBindings", "class_vertices_engine_1_1_input_1_1vx_key_bindings.html", "class_vertices_engine_1_1_input_1_1vx_key_bindings" ],
        [ "vxPlayerInputComponent", "class_vertices_engine_1_1_input_1_1vx_player_input_component.html", "class_vertices_engine_1_1_input_1_1vx_player_input_component" ]
      ] ],
      [ "Localization", "namespace_vertices_engine_1_1_localization.html", [
        [ "UI", "namespace_vertices_engine_1_1_localization_1_1_u_i.html", [
          [ "vxLocalizationSelectMsgBox", "class_vertices_engine_1_1_localization_1_1_u_i_1_1vx_localization_select_msg_box.html", "class_vertices_engine_1_1_localization_1_1_u_i_1_1vx_localization_select_msg_box" ],
          [ "vxLocComboBox", "class_vertices_engine_1_1_localization_1_1_u_i_1_1vx_loc_combo_box.html", "class_vertices_engine_1_1_localization_1_1_u_i_1_1vx_loc_combo_box" ],
          [ "vxLocComboBoxItem", "class_vertices_engine_1_1_localization_1_1_u_i_1_1vx_loc_combo_box_item.html", "class_vertices_engine_1_1_localization_1_1_u_i_1_1vx_loc_combo_box_item" ]
        ] ]
      ] ],
      [ "Mathematics", "namespace_vertices_engine_1_1_mathematics.html", [
        [ "vxSpline", "class_vertices_engine_1_1_mathematics_1_1vx_spline.html", "class_vertices_engine_1_1_mathematics_1_1vx_spline" ],
        [ "vxSplineNode", "class_vertices_engine_1_1_mathematics_1_1vx_spline_node.html", "class_vertices_engine_1_1_mathematics_1_1vx_spline_node" ]
      ] ],
      [ "Monetization", "namespace_vertices_engine_1_1_monetization.html", [
        [ "Ads", "namespace_vertices_engine_1_1_monetization_1_1_ads.html", [
          [ "vxAdManager", "class_vertices_engine_1_1_monetization_1_1_ads_1_1vx_ad_manager.html", "class_vertices_engine_1_1_monetization_1_1_ads_1_1vx_ad_manager" ],
          [ "vxGenericAdProvider", "class_vertices_engine_1_1_monetization_1_1_ads_1_1vx_generic_ad_provider.html", null ],
          [ "vxGenericBannerAd", "class_vertices_engine_1_1_monetization_1_1_ads_1_1vx_generic_banner_ad.html", "class_vertices_engine_1_1_monetization_1_1_ads_1_1vx_generic_banner_ad" ],
          [ "vxGenericInterstitialAd", "class_vertices_engine_1_1_monetization_1_1_ads_1_1vx_generic_interstitial_ad.html", "class_vertices_engine_1_1_monetization_1_1_ads_1_1vx_generic_interstitial_ad" ],
          [ "vxGenericRewardAd", "class_vertices_engine_1_1_monetization_1_1_ads_1_1vx_generic_reward_ad.html", "class_vertices_engine_1_1_monetization_1_1_ads_1_1vx_generic_reward_ad" ],
          [ "vxIAdProvider", "interface_vertices_engine_1_1_monetization_1_1_ads_1_1vx_i_ad_provider.html", null ],
          [ "vxIBannerAd", "interface_vertices_engine_1_1_monetization_1_1_ads_1_1vx_i_banner_ad.html", "interface_vertices_engine_1_1_monetization_1_1_ads_1_1vx_i_banner_ad" ],
          [ "vxIInterstitialAd", "interface_vertices_engine_1_1_monetization_1_1_ads_1_1vx_i_interstitial_ad.html", "interface_vertices_engine_1_1_monetization_1_1_ads_1_1vx_i_interstitial_ad" ],
          [ "vxIRewardAd", "interface_vertices_engine_1_1_monetization_1_1_ads_1_1vx_i_reward_ad.html", "interface_vertices_engine_1_1_monetization_1_1_ads_1_1vx_i_reward_ad" ]
        ] ],
        [ "Purchases", "namespace_vertices_engine_1_1_monetization_1_1_purchases.html", [
          [ "vxIInAppPurchaseProvider", "interface_vertices_engine_1_1_monetization_1_1_purchases_1_1vx_i_in_app_purchase_provider.html", "interface_vertices_engine_1_1_monetization_1_1_purchases_1_1vx_i_in_app_purchase_provider" ],
          [ "vxInAppProduct", "class_vertices_engine_1_1_monetization_1_1_purchases_1_1vx_in_app_product.html", "class_vertices_engine_1_1_monetization_1_1_purchases_1_1vx_in_app_product" ],
          [ "vxInAppProductManager", "class_vertices_engine_1_1_monetization_1_1_purchases_1_1vx_in_app_product_manager.html", "class_vertices_engine_1_1_monetization_1_1_purchases_1_1vx_in_app_product_manager" ],
          [ "vxInAppPurchaseEventArgs", "class_vertices_engine_1_1_monetization_1_1_purchases_1_1vx_in_app_purchase_event_args.html", null ],
          [ "vxInAppPurchaseProviderForSteam", "class_vertices_engine_1_1_monetization_1_1_purchases_1_1vx_in_app_purchase_provider_for_steam.html", "class_vertices_engine_1_1_monetization_1_1_purchases_1_1vx_in_app_purchase_provider_for_steam" ]
        ] ]
      ] ],
      [ "Net", "namespace_vertices_engine_1_1_net.html", [
        [ "Events", "namespace_vertices_engine_1_1_net_1_1_events.html", [
          [ "vxGameServerListRecievedEventArgs", "class_vertices_engine_1_1_net_1_1_events_1_1vx_game_server_list_recieved_event_args.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_game_server_list_recieved_event_args" ],
          [ "vxNetClientEvent_NetSessionStateChanged", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event___net_session_state_changed.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event___net_session_state_changed" ],
          [ "vxNetClientEventConnected", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_connected.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_connected" ],
          [ "vxNetClientEventDisconnected", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_disconnected.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_disconnected" ],
          [ "vxNetClientEventDiscoverySignalResponse", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_discovery_signal_response.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_discovery_signal_response" ],
          [ "vxNetClientEventPlayerConnected", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_player_connected.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_player_connected" ],
          [ "vxNetClientEventPlayerDisconnected", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_player_disconnected.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_player_disconnected" ],
          [ "vxNetClientEventPlayerStatusUpdate", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_player_status_update.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_player_status_update" ],
          [ "vxNetClientEventSessionStatusUpdated", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_session_status_updated.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_client_event_session_status_updated" ],
          [ "vxNetServerEventClientConnected", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_client_connected.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_client_connected" ],
          [ "vxNetServerEventClientDisconnected", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_client_disconnected.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_client_disconnected" ],
          [ "vxNetServerEventDiscoverySignalRequest", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_discovery_signal_request.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_discovery_signal_request" ],
          [ "vxNetServerEventPlayerJoined", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_player_joined.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_player_joined" ],
          [ "vxNetServerEventPlayerStateUpdate", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_player_state_update.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_player_state_update" ],
          [ "vxNetServerEventPlayerStatusUpdate", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_player_status_update.html", "class_vertices_engine_1_1_net_1_1_events_1_1vx_net_server_event_player_status_update" ]
        ] ],
        [ "Messages", "namespace_vertices_engine_1_1_net_1_1_messages.html", [
          [ "vxINetMessageIncoming", "interface_vertices_engine_1_1_net_1_1_messages_1_1vx_i_net_message_incoming.html", null ],
          [ "vxINetMessageOutgoing", "interface_vertices_engine_1_1_net_1_1_messages_1_1vx_i_net_message_outgoing.html", null ],
          [ "vxINetworkMessage", "interface_vertices_engine_1_1_net_1_1_messages_1_1vx_i_network_message.html", "interface_vertices_engine_1_1_net_1_1_messages_1_1vx_i_network_message" ],
          [ "vxNetmsgAddPlayer", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_add_player.html", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_add_player" ],
          [ "vxNetmsgLevelEvent", "class_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_level_event.html", "class_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_level_event" ],
          [ "vxNetmsgLevelMetaData", "class_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_level_meta_data.html", "class_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_level_meta_data" ],
          [ "vxNetmsgPlayerMetaData", "class_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_player_meta_data.html", "class_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_player_meta_data" ],
          [ "vxNetmsgRemovePlayer", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_remove_player.html", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_remove_player" ],
          [ "vxNetMsgServerInfo", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_net_msg_server_info.html", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_net_msg_server_info" ],
          [ "vxNetmsgServerShutdown", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_server_shutdown.html", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_server_shutdown" ],
          [ "vxNetmsgSetPlayerAsHost", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_set_player_as_host.html", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_set_player_as_host" ],
          [ "vxNetmsgSpawnItem", "class_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_spawn_item.html", "class_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_spawn_item" ],
          [ "vxNetmsgUpdatePlayerEntityState", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_update_player_entity_state.html", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_update_player_entity_state" ],
          [ "vxNetmsgUpdatePlayerList", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_update_player_list.html", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_update_player_list" ],
          [ "vxNetmsgUpdatePlayerLobbyStatus", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_update_player_lobby_status.html", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_update_player_lobby_status" ],
          [ "vxNetmsgUpdateSessionState", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_update_session_state.html", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_update_session_state" ],
          [ "vxNetmsgUpdateSessionStatus", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_update_session_status.html", "struct_vertices_engine_1_1_net_1_1_messages_1_1vx_netmsg_update_session_status" ]
        ] ],
        [ "UI", "namespace_vertices_engine_1_1_net_1_1_u_i.html", [
          [ "vxServerListDialog", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_server_list_dialog.html", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_server_list_dialog" ],
          [ "vxServerListItem", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_server_list_item.html", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_server_list_item" ],
          [ "vxServerLobbyDialog", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_server_lobby_dialog.html", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_server_lobby_dialog" ],
          [ "vxServerLobbyPlayerItem", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_server_lobby_player_item.html", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_server_lobby_player_item" ],
          [ "vxSeverLANListDialog", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_sever_l_a_n_list_dialog.html", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_sever_l_a_n_list_dialog" ],
          [ "vxSeverLobbyDialog", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_sever_lobby_dialog.html", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_sever_lobby_dialog" ],
          [ "vxSeverOnlineListDialog", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_sever_online_list_dialog.html", "class_vertices_engine_1_1_net_1_1_u_i_1_1vx_sever_online_list_dialog" ]
        ] ],
        [ "INetworkSessionManager", "interface_vertices_engine_1_1_net_1_1_i_network_session_manager.html", "interface_vertices_engine_1_1_net_1_1_i_network_session_manager" ],
        [ "vxINetGameplayScene", "interface_vertices_engine_1_1_net_1_1vx_i_net_gameplay_scene.html", "interface_vertices_engine_1_1_net_1_1vx_i_net_gameplay_scene" ],
        [ "vxINetworkClientBackend", "interface_vertices_engine_1_1_net_1_1vx_i_network_client_backend.html", "interface_vertices_engine_1_1_net_1_1vx_i_network_client_backend" ],
        [ "vxINetworkConfig", "interface_vertices_engine_1_1_net_1_1vx_i_network_config.html", "interface_vertices_engine_1_1_net_1_1vx_i_network_config" ],
        [ "vxINetworkServerBackend", "interface_vertices_engine_1_1_net_1_1vx_i_network_server_backend.html", "interface_vertices_engine_1_1_net_1_1vx_i_network_server_backend" ],
        [ "vxNetBuffer", "class_vertices_engine_1_1_net_1_1vx_net_buffer.html", null ],
        [ "vxNetBufferTests", "class_vertices_engine_1_1_net_1_1vx_net_buffer_tests.html", null ],
        [ "vxNetEntity3DState", "class_vertices_engine_1_1_net_1_1vx_net_entity3_d_state.html", "class_vertices_engine_1_1_net_1_1vx_net_entity3_d_state" ],
        [ "vxNetEntityState", "class_vertices_engine_1_1_net_1_1vx_net_entity_state.html", null ],
        [ "vxNetPlayerInfo", "struct_vertices_engine_1_1_net_1_1vx_net_player_info.html", "struct_vertices_engine_1_1_net_1_1vx_net_player_info" ],
        [ "vxNetPlayerManager", "class_vertices_engine_1_1_net_1_1vx_net_player_manager.html", "class_vertices_engine_1_1_net_1_1vx_net_player_manager" ],
        [ "vxNetworkClient", "class_vertices_engine_1_1_net_1_1vx_network_client.html", "class_vertices_engine_1_1_net_1_1vx_network_client" ],
        [ "vxNetworkManager", "class_vertices_engine_1_1_net_1_1vx_network_manager.html", "class_vertices_engine_1_1_net_1_1vx_network_manager" ],
        [ "vxNetworkServer", "class_vertices_engine_1_1_net_1_1vx_network_server.html", "class_vertices_engine_1_1_net_1_1vx_network_server" ]
      ] ],
      [ "Particles", "namespace_vertices_engine_1_1_particles.html", [
        [ "vxIParticle", "interface_vertices_engine_1_1_particles_1_1vx_i_particle.html", "interface_vertices_engine_1_1_particles_1_1vx_i_particle" ],
        [ "vxParticle2D", "class_vertices_engine_1_1_particles_1_1vx_particle2_d.html", "class_vertices_engine_1_1_particles_1_1vx_particle2_d" ],
        [ "vxParticle3D", "class_vertices_engine_1_1_particles_1_1vx_particle3_d.html", "class_vertices_engine_1_1_particles_1_1vx_particle3_d" ],
        [ "vxParticlePool", "class_vertices_engine_1_1_particles_1_1vx_particle_pool.html", "class_vertices_engine_1_1_particles_1_1vx_particle_pool" ],
        [ "vxParticlePoolDefinition", "class_vertices_engine_1_1_particles_1_1vx_particle_pool_definition.html", null ],
        [ "vxParticleSystem", "class_vertices_engine_1_1_particles_1_1vx_particle_system.html", "class_vertices_engine_1_1_particles_1_1vx_particle_system" ],
        [ "vxParticleSystemManager", "class_vertices_engine_1_1_particles_1_1vx_particle_system_manager.html", "class_vertices_engine_1_1_particles_1_1vx_particle_system_manager" ],
        [ "vxRegisterAsParticleSystemAttribute", "class_vertices_engine_1_1_particles_1_1vx_register_as_particle_system_attribute.html", "class_vertices_engine_1_1_particles_1_1vx_register_as_particle_system_attribute" ]
      ] ],
      [ "Physics", "namespace_vertices_engine_1_1_physics.html", [
        [ "BEPU", "namespace_vertices_engine_1_1_physics_1_1_b_e_p_u.html", [
          [ "vxBEPUPhysicsSystem", "class_vertices_engine_1_1_physics_1_1_b_e_p_u_1_1vx_b_e_p_u_physics_system.html", "class_vertices_engine_1_1_physics_1_1_b_e_p_u_1_1vx_b_e_p_u_physics_system" ]
        ] ],
        [ "BEPUWrapper", "namespace_vertices_engine_1_1_physics_1_1_b_e_p_u_wrapper.html", [
          [ "vxBEPUPhysicsBoxCollider", "class_vertices_engine_1_1_physics_1_1_b_e_p_u_wrapper_1_1vx_b_e_p_u_physics_box_collider.html", "class_vertices_engine_1_1_physics_1_1_b_e_p_u_wrapper_1_1vx_b_e_p_u_physics_box_collider" ],
          [ "vxBEPUPhysicsCapsuleCollider", "class_vertices_engine_1_1_physics_1_1_b_e_p_u_wrapper_1_1vx_b_e_p_u_physics_capsule_collider.html", "class_vertices_engine_1_1_physics_1_1_b_e_p_u_wrapper_1_1vx_b_e_p_u_physics_capsule_collider" ],
          [ "vxBEPUPhysicsSphereCollider", "class_vertices_engine_1_1_physics_1_1_b_e_p_u_wrapper_1_1vx_b_e_p_u_physics_sphere_collider.html", "class_vertices_engine_1_1_physics_1_1_b_e_p_u_wrapper_1_1vx_b_e_p_u_physics_sphere_collider" ],
          [ "vxBEPUPhysicsStaticMeshCollider", "class_vertices_engine_1_1_physics_1_1_b_e_p_u_wrapper_1_1vx_b_e_p_u_physics_static_mesh_collider.html", "class_vertices_engine_1_1_physics_1_1_b_e_p_u_wrapper_1_1vx_b_e_p_u_physics_static_mesh_collider" ]
        ] ],
        [ "Entities", "namespace_vertices_engine_1_1_physics_1_1_entities.html", [
          [ "vxPhysics2DCircleCollider", "interface_vertices_engine_1_1_physics_1_1_entities_1_1vx_physics2_d_circle_collider.html", null ],
          [ "vxPhysics2DEntity", "interface_vertices_engine_1_1_physics_1_1_entities_1_1vx_physics2_d_entity.html", null ],
          [ "vxPhysics2DRectCollider", "interface_vertices_engine_1_1_physics_1_1_entities_1_1vx_physics2_d_rect_collider.html", null ]
        ] ],
        [ "vxBEPUPhysicsBaseCollider", "class_vertices_engine_1_1_physics_1_1vx_b_e_p_u_physics_base_collider.html", "class_vertices_engine_1_1_physics_1_1vx_b_e_p_u_physics_base_collider" ],
        [ "vxBoxCollider", "interface_vertices_engine_1_1_physics_1_1vx_box_collider.html", null ],
        [ "vxCapsuleCollider", "interface_vertices_engine_1_1_physics_1_1vx_capsule_collider.html", "interface_vertices_engine_1_1_physics_1_1vx_capsule_collider" ],
        [ "vxIPhysicsLibraryWrapper", "interface_vertices_engine_1_1_physics_1_1vx_i_physics_library_wrapper.html", null ],
        [ "vxPhysicsCollider3D", "interface_vertices_engine_1_1_physics_1_1vx_physics_collider3_d.html", "interface_vertices_engine_1_1_physics_1_1vx_physics_collider3_d" ],
        [ "vxPhysicsSystem", "class_vertices_engine_1_1_physics_1_1vx_physics_system.html", "class_vertices_engine_1_1_physics_1_1vx_physics_system" ],
        [ "vxSphereCollider", "interface_vertices_engine_1_1_physics_1_1vx_sphere_collider.html", "interface_vertices_engine_1_1_physics_1_1vx_sphere_collider" ],
        [ "vxStaticMeshCollider", "interface_vertices_engine_1_1_physics_1_1vx_static_mesh_collider.html", null ]
      ] ],
      [ "Plugins", "namespace_vertices_engine_1_1_plugins.html", [
        [ "Mods", "namespace_vertices_engine_1_1_plugins_1_1_mods.html", [
          [ "vxModConfig", "class_vertices_engine_1_1_plugins_1_1_mods_1_1vx_mod_config.html", "class_vertices_engine_1_1_plugins_1_1_mods_1_1vx_mod_config" ],
          [ "vxModItemStatus", "struct_vertices_engine_1_1_plugins_1_1_mods_1_1vx_mod_item_status.html", "struct_vertices_engine_1_1_plugins_1_1_mods_1_1vx_mod_item_status" ]
        ] ],
        [ "vxIPlugin", "interface_vertices_engine_1_1_plugins_1_1vx_i_plugin.html", "interface_vertices_engine_1_1_plugins_1_1vx_i_plugin" ],
        [ "vxPluginManager", "class_vertices_engine_1_1_plugins_1_1vx_plugin_manager.html", "class_vertices_engine_1_1_plugins_1_1vx_plugin_manager" ],
        [ "vxPluginMetadata", "class_vertices_engine_1_1_plugins_1_1vx_plugin_metadata.html", null ]
      ] ],
      [ "Profile", "namespace_vertices_engine_1_1_profile.html", [
        [ "vxAchievement", "class_vertices_engine_1_1_profile_1_1vx_achievement.html", "class_vertices_engine_1_1_profile_1_1vx_achievement" ],
        [ "vxIPlayerProfile", "interface_vertices_engine_1_1_profile_1_1vx_i_player_profile.html", "interface_vertices_engine_1_1_profile_1_1vx_i_player_profile" ],
        [ "vxLeaderboard", "class_vertices_engine_1_1_profile_1_1vx_leaderboard.html", "class_vertices_engine_1_1_profile_1_1vx_leaderboard" ],
        [ "vxPlatform", "class_vertices_engine_1_1_profile_1_1vx_platform.html", "class_vertices_engine_1_1_profile_1_1vx_platform" ],
        [ "vxPlayerProfileGenericWrapper", "class_vertices_engine_1_1_profile_1_1vx_player_profile_generic_wrapper.html", "class_vertices_engine_1_1_profile_1_1vx_player_profile_generic_wrapper" ]
      ] ],
      [ "Screens", "namespace_vertices_engine_1_1_screens.html", [
        [ "Async", "namespace_vertices_engine_1_1_screens_1_1_async.html", [
          [ "BusyScreen", "class_vertices_engine_1_1_screens_1_1_async_1_1_busy_screen.html", "class_vertices_engine_1_1_screens_1_1_async_1_1_busy_screen" ],
          [ "vxLoadingScreen", "class_vertices_engine_1_1_screens_1_1_async_1_1vx_loading_screen.html", "class_vertices_engine_1_1_screens_1_1_async_1_1vx_loading_screen" ],
          [ "vxStartupMenuScreen", "class_vertices_engine_1_1_screens_1_1_async_1_1vx_startup_menu_screen.html", "class_vertices_engine_1_1_screens_1_1_async_1_1vx_startup_menu_screen" ]
        ] ],
        [ "vxModelViewer", "class_vertices_engine_1_1_screens_1_1vx_model_viewer.html", "class_vertices_engine_1_1_screens_1_1vx_model_viewer" ]
      ] ],
      [ "Serilization", "namespace_vertices_engine_1_1_serilization.html", [
        [ "EngineInfo", "class_vertices_engine_1_1_serilization_1_1_engine_info.html", null ],
        [ "GameInfo", "class_vertices_engine_1_1_serilization_1_1_game_info.html", null ],
        [ "SandboxFileInfo", "class_vertices_engine_1_1_serilization_1_1_sandbox_file_info.html", null ],
        [ "vxFileInfo", "class_vertices_engine_1_1_serilization_1_1vx_file_info.html", null ],
        [ "vxFogState", "class_vertices_engine_1_1_serilization_1_1vx_fog_state.html", null ],
        [ "vxGraphicalAntiAliasingSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_anti_aliasing_settings.html", null ],
        [ "vxGraphicalBaseBooleanSetting", "class_vertices_engine_1_1_serilization_1_1vx_graphical_base_boolean_setting.html", "class_vertices_engine_1_1_serilization_1_1vx_graphical_base_boolean_setting" ],
        [ "vxGraphicalBaseQualitySetting", "class_vertices_engine_1_1_serilization_1_1vx_graphical_base_quality_setting.html", "class_vertices_engine_1_1_serilization_1_1vx_graphical_base_quality_setting" ],
        [ "vxGraphicalBloomSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_bloom_settings.html", null ],
        [ "vxGraphicalBlurSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_blur_settings.html", null ],
        [ "vxGraphicalDefferredLightingSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_defferred_lighting_settings.html", null ],
        [ "vxGraphicalDepthOfFieldSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_depth_of_field_settings.html", null ],
        [ "vxGraphicalEdgeDetectionSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_edge_detection_settings.html", null ],
        [ "vxGraphicalGodRaysSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_god_rays_settings.html", null ],
        [ "vxGraphicalMotionBlurSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_motion_blur_settings.html", null ],
        [ "vxGraphicalReflectionSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_reflection_settings.html", null ],
        [ "vxGraphicalShadowSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_shadow_settings.html", null ],
        [ "vxGraphicalSSAOSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_s_s_a_o_settings.html", null ],
        [ "vxGraphicalSSRSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_s_s_r_settings.html", null ],
        [ "vxGraphicalTexturesSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_textures_settings.html", "class_vertices_engine_1_1_serilization_1_1vx_graphical_textures_settings" ],
        [ "vxSerializableColor", "class_vertices_engine_1_1_serilization_1_1vx_serializable_color.html", null ],
        [ "vxSerializableEntityState2D", "class_vertices_engine_1_1_serilization_1_1vx_serializable_entity_state2_d.html", null ],
        [ "vxSerializableEntityState3D", "class_vertices_engine_1_1_serilization_1_1vx_serializable_entity_state3_d.html", null ],
        [ "vxSerializableEnviroment", "class_vertices_engine_1_1_serilization_1_1vx_serializable_enviroment.html", null ],
        [ "vxSerializableImportedEntityInfo3D", "class_vertices_engine_1_1_serilization_1_1vx_serializable_imported_entity_info3_d.html", "class_vertices_engine_1_1_serilization_1_1vx_serializable_imported_entity_info3_d" ],
        [ "vxSerializableScene2DData", "class_vertices_engine_1_1_serilization_1_1vx_serializable_scene2_d_data.html", null ],
        [ "vxSerializableScene3DData", "class_vertices_engine_1_1_serilization_1_1vx_serializable_scene3_d_data.html", null ],
        [ "vxSerializableSceneBaseData", "class_vertices_engine_1_1_serilization_1_1vx_serializable_scene_base_data.html", null ],
        [ "vxSerializableTerrainData", "class_vertices_engine_1_1_serilization_1_1vx_serializable_terrain_data.html", null ],
        [ "vxSerializableTerrainVertex", "class_vertices_engine_1_1_serilization_1_1vx_serializable_terrain_vertex.html", null ],
        [ "vxSerializableTexture2D", "class_vertices_engine_1_1_serilization_1_1vx_serializable_texture2_d.html", null ],
        [ "vxSerializableVersion", "class_vertices_engine_1_1_serilization_1_1vx_serializable_version.html", null ],
        [ "vxSkyBoxState", "class_vertices_engine_1_1_serilization_1_1vx_sky_box_state.html", null ],
        [ "WorkshopFileInfo", "class_vertices_engine_1_1_serilization_1_1_workshop_file_info.html", null ]
      ] ],
      [ "Settings", "namespace_vertices_engine_1_1_settings.html", [
        [ "vxGraphicalSettings", "class_vertices_engine_1_1_settings_1_1vx_graphical_settings.html", "class_vertices_engine_1_1_settings_1_1vx_graphical_settings" ]
      ] ],
      [ "UI", "namespace_vertices_engine_1_1_u_i.html", [
        [ "Controls", "namespace_vertices_engine_1_1_u_i_1_1_controls.html", [
          [ "Commands", "namespace_vertices_engine_1_1_u_i_1_1_controls_1_1_commands.html", [
            [ "PropertyEntityStruct", "class_vertices_engine_1_1_u_i_1_1_controls_1_1_commands_1_1_property_entity_struct.html", null ],
            [ "vxCMDPropertyValueChange", "class_vertices_engine_1_1_u_i_1_1_controls_1_1_commands_1_1vx_c_m_d_property_value_change.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1_commands_1_1vx_c_m_d_property_value_change" ]
          ] ],
          [ "PropertiesTextboxArtProvider", "class_vertices_engine_1_1_u_i_1_1_controls_1_1_properties_textbox_art_provider.html", null ],
          [ "vxAttributeCategory", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_attribute_category.html", null ],
          [ "vxButtonControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_button_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_button_control" ],
          [ "vxButtonImageControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_button_image_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_button_image_control" ],
          [ "vxCanvas", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_canvas.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_canvas" ],
          [ "vxComboBox", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_combo_box.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_combo_box" ],
          [ "vxComboBoxItem", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_combo_box_item.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_combo_box_item" ],
          [ "vxImage", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_image.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_image" ],
          [ "vxIncrementControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_increment_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_increment_control" ],
          [ "vxKeyBindingSettingsGUIItem", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_key_binding_settings_g_u_i_item.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_key_binding_settings_g_u_i_item" ],
          [ "vxLabel", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_label.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_label" ],
          [ "vxListView", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_list_view.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_list_view" ],
          [ "vxListViewItem", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_list_view_item.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_list_view_item" ],
          [ "vxListViewScrollBar", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_list_view_scroll_bar.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_list_view_scroll_bar" ],
          [ "vxListViewSpliter", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_list_view_spliter.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_list_view_spliter" ],
          [ "vxManageImportedEntityUIItem", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_manage_imported_entity_u_i_item.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_manage_imported_entity_u_i_item" ],
          [ "vxMenuEntry", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_menu_entry.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_menu_entry" ],
          [ "vxNotification", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_notification.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_notification" ],
          [ "vxNotificationManager", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_notification_manager.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_notification_manager" ],
          [ "vxPanel", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_panel.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_panel" ],
          [ "vxPropertiesControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_properties_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_properties_control" ],
          [ "vxPropertiesScrollPanelControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_properties_scroll_panel_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_properties_scroll_panel_control" ],
          [ "vxPropertyAttributePair", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_attribute_pair.html", null ],
          [ "vxPropertyComboBox", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_combo_box.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_combo_box" ],
          [ "vxPropertyControlCheckBox", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_check_box.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_check_box" ],
          [ "vxPropertyControlColour", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_colour.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_colour" ],
          [ "vxPropertyControlFloatRange", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_float_range.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_float_range" ],
          [ "vxPropertyControlFloatTextbox", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_float_textbox.html", null ],
          [ "vxPropertyControlGameObject", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_game_object.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_game_object" ],
          [ "vxPropertyControlSelectEventArgs", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_select_event_args.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_select_event_args" ],
          [ "vxPropertyControlTextbox", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_textbox.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_textbox" ],
          [ "vxPropertyControlTexture2D", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_texture2_d.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_control_texture2_d" ],
          [ "vxPropertyGroup", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_group.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_group" ],
          [ "vxPropertyItemBaseClass", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_base_class.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_base_class" ],
          [ "vxPropertyItemBool", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_bool.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_bool" ],
          [ "vxPropertyItemChoices", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_choices.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_choices" ],
          [ "vxPropertyItemColour", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_colour.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_colour" ],
          [ "vxPropertyItemFloat", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_float.html", null ],
          [ "vxPropertyItemFloatArray", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_float_array.html", null ],
          [ "vxPropertyItemFloatRange", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_float_range.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_float_range" ],
          [ "vxPropertyItemGameObject", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_game_object.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_game_object" ],
          [ "vxPropertyItemInt", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_int.html", null ],
          [ "vxPropertyItemIntTextbox", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_int_textbox.html", null ],
          [ "vxPropertyItemList", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_list.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_list" ],
          [ "vxPropertyItemModel", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_model.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_model" ],
          [ "vxPropertyItemModelMesh", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_model_mesh.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_model_mesh" ],
          [ "vxPropertyItemTexture2D", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_texture2_d.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_texture2_d" ],
          [ "vxPropertyItemTexture2DLargeView", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_texture2_d_large_view.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_texture2_d_large_view" ],
          [ "vxPropertyItemVector2", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_vector2.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_vector2" ],
          [ "vxPropertyItemVector3", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_vector3.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_property_item_vector3" ],
          [ "vxRibbonButtonControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_button_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_button_control" ],
          [ "vxRibbonContextualTabPage", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_contextual_tab_page.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_contextual_tab_page" ],
          [ "vxRibbonControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_control" ],
          [ "vxRibbonControlGroup", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_control_group.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_control_group" ],
          [ "vxRibbonDropdownControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_dropdown_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_dropdown_control" ],
          [ "vxRibbonLabelControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_label_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_label_control" ],
          [ "vxRibbonTabPage", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_tab_page.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_tab_page" ],
          [ "vxRibbonToolbar", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_toolbar.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_toolbar" ],
          [ "vxRibbonToolbarButtonControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_toolbar_button_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_toolbar_button_control" ],
          [ "vxRibbonToolbarLogoButtonControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_toolbar_logo_button_control.html", null ],
          [ "vxRibbonToolbarSplitterControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_toolbar_splitter_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_ribbon_toolbar_splitter_control" ],
          [ "vxSandboxImportedItemButton", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_sandbox_imported_item_button.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_sandbox_imported_item_button" ],
          [ "vxSandboxItemButton", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_sandbox_item_button.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_sandbox_item_button" ],
          [ "vxScrollBar", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_bar.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_bar" ],
          [ "vxScrollPanel", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_panel.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_panel" ],
          [ "vxScrollPanelComboxBoxItem", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_panel_combox_box_item.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_panel_combox_box_item" ],
          [ "vxScrollPanelIncrementItem", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_panel_increment_item.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_panel_increment_item" ],
          [ "vxScrollPanelSliderItem", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_panel_slider_item.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_panel_slider_item" ],
          [ "vxScrollPanelSpliter", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_panel_spliter.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_scroll_panel_spliter" ],
          [ "vxSettingsGUIItem", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_settings_g_u_i_item.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_settings_g_u_i_item" ],
          [ "vxSettingsReadOnlyGUIItem", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_settings_read_only_g_u_i_item.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_settings_read_only_g_u_i_item" ],
          [ "vxSlidePageTabArtProvider", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_slide_page_tab_art_provider.html", null ],
          [ "vxSlider", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_slider.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_slider" ],
          [ "vxSliderMarker", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_slider_marker.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_slider_marker" ],
          [ "vxSlideTabControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_slide_tab_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_slide_tab_control" ],
          [ "vxSlideTabPage", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_slide_tab_page.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_slide_tab_page" ],
          [ "vxSlideTabPageTab", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_slide_tab_page_tab.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_slide_tab_page_tab" ],
          [ "vxSpinnerControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_spinner_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_spinner_control" ],
          [ "vxTabControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_tab_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_tab_control" ],
          [ "vxTabPageControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_tab_page_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_tab_page_control" ],
          [ "vxTabPageTab", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_tab_page_tab.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_tab_page_tab" ],
          [ "vxTextbox", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_textbox.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_textbox" ],
          [ "vxToggleImageButton", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_toggle_image_button.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_toggle_image_button" ],
          [ "vxToolbar", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_toolbar.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_toolbar" ],
          [ "vxToolbarButton", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_toolbar_button.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_toolbar_button" ],
          [ "vxToolbarSpliter", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_toolbar_spliter.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_toolbar_spliter" ],
          [ "vxTreeControl", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_tree_control.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_tree_control" ],
          [ "vxTreeNode", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_tree_node.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_tree_node" ],
          [ "vxTxtrPaintToolbarButton", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_txtr_paint_toolbar_button.html", "class_vertices_engine_1_1_u_i_1_1_controls_1_1vx_txtr_paint_toolbar_button" ]
        ] ],
        [ "Dialogs", "namespace_vertices_engine_1_1_u_i_1_1_dialogs.html", [
          [ "Utilities", "namespace_vertices_engine_1_1_u_i_1_1_dialogs_1_1_utilities.html", [
            [ "vxTexPackGenDialog", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1_utilities_1_1vx_tex_pack_gen_dialog.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1_utilities_1_1vx_tex_pack_gen_dialog" ]
          ] ],
          [ "vxAudioMenuScreen", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_audio_menu_screen.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_audio_menu_screen" ],
          [ "vxContextMenuControl", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_context_menu_control.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_context_menu_control" ],
          [ "vxContextMenuItem", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_context_menu_item.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_context_menu_item" ],
          [ "vxContextMenuSplitter", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_context_menu_splitter.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_context_menu_splitter" ],
          [ "vxDebugMenuScreen", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_debug_menu_screen.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_debug_menu_screen" ],
          [ "vxDebugSettingsDialog", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_debug_settings_dialog.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_debug_settings_dialog" ],
          [ "vxDialogBase", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_dialog_base.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_dialog_base" ],
          [ "vxFileDialogItem", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_dialog_item.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_dialog_item" ],
          [ "vxFileExplorerDialog", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_explorer_dialog.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_explorer_dialog" ],
          [ "vxFileExplorerDirectoryItem", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_explorer_directory_item.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_explorer_directory_item" ],
          [ "vxFileExplorerItem", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_explorer_item.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_explorer_item" ],
          [ "vxFileExplorerURLBar", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_explorer_u_r_l_bar.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_explorer_u_r_l_bar" ],
          [ "vxFileExplorerURLBarButton", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_explorer_u_r_l_bar_button.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_explorer_u_r_l_bar_button" ],
          [ "vxFileExplorerURLBarSplitter", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_file_explorer_u_r_l_bar_splitter.html", null ],
          [ "vxGraphicSettingsDialog", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_graphic_settings_dialog.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_graphic_settings_dialog" ],
          [ "vxKeyboardSettingsDialog", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_keyboard_settings_dialog.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_keyboard_settings_dialog" ],
          [ "vxLocalizationDialog", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_localization_dialog.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_localization_dialog" ],
          [ "vxModDialoglItem", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_mod_dialogl_item.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_mod_dialogl_item" ],
          [ "vxModManagerDialog", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_mod_manager_dialog.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_mod_manager_dialog" ],
          [ "vxOpenSandboxFileDialog", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_open_sandbox_file_dialog.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_open_sandbox_file_dialog" ],
          [ "vxSandboxFileSelectedEventArgs", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_sandbox_file_selected_event_args.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_sandbox_file_selected_event_args" ],
          [ "vxSandboxNewItemDialog", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_sandbox_new_item_dialog.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_sandbox_new_item_dialog" ],
          [ "vxScrollPanelItem", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_scroll_panel_item.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_scroll_panel_item" ],
          [ "vxSettingsBaseDialog", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_settings_base_dialog.html", "class_vertices_engine_1_1_u_i_1_1_dialogs_1_1vx_settings_base_dialog" ]
        ] ],
        [ "Events", "namespace_vertices_engine_1_1_u_i_1_1_events.html", [
          [ "vxComboBoxSelectionChangedEventArgs", "class_vertices_engine_1_1_u_i_1_1_events_1_1vx_combo_box_selection_changed_event_args.html", "class_vertices_engine_1_1_u_i_1_1_events_1_1vx_combo_box_selection_changed_event_args" ],
          [ "vxFileDialogItemClickEventArgs", "class_vertices_engine_1_1_u_i_1_1_events_1_1vx_file_dialog_item_click_event_args.html", "class_vertices_engine_1_1_u_i_1_1_events_1_1vx_file_dialog_item_click_event_args" ],
          [ "vxUIControlClickEventArgs", "class_vertices_engine_1_1_u_i_1_1_events_1_1vx_u_i_control_click_event_args.html", "class_vertices_engine_1_1_u_i_1_1_events_1_1vx_u_i_control_click_event_args" ],
          [ "vxUIManagerItemAddEventArgs", "class_vertices_engine_1_1_u_i_1_1_events_1_1vx_u_i_manager_item_add_event_args.html", "class_vertices_engine_1_1_u_i_1_1_events_1_1vx_u_i_manager_item_add_event_args" ],
          [ "vxValueChangedEventArgs", "class_vertices_engine_1_1_u_i_1_1_events_1_1vx_value_changed_event_args.html", "class_vertices_engine_1_1_u_i_1_1_events_1_1vx_value_changed_event_args" ]
        ] ],
        [ "Menus", "namespace_vertices_engine_1_1_u_i_1_1_menus.html", [
          [ "vxControlsMenuScreen", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_controls_menu_screen.html", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_controls_menu_screen" ],
          [ "vxLocalizationMenuScreen", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_localization_menu_screen.html", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_localization_menu_screen" ],
          [ "vxLocalizationUpdateScreen", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_localization_update_screen.html", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_localization_update_screen" ],
          [ "vxMenuBaseScreen", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_menu_base_screen.html", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_menu_base_screen" ],
          [ "vxPauseMenuScreen", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_pause_menu_screen.html", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_pause_menu_screen" ],
          [ "vxProfileMenuScreen", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_profile_menu_screen.html", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_profile_menu_screen" ],
          [ "vxPurchaseMenuScreen", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_purchase_menu_screen.html", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_purchase_menu_screen" ],
          [ "vxSettingsMenuScreen", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_settings_menu_screen.html", "class_vertices_engine_1_1_u_i_1_1_menus_1_1vx_settings_menu_screen" ]
        ] ],
        [ "MessageBoxs", "namespace_vertices_engine_1_1_u_i_1_1_message_boxs.html", [
          [ "vxAboutBox", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_about_box.html", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_about_box" ],
          [ "vxMessageBox", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_message_box.html", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_message_box" ],
          [ "vxMessageBoxNetworkLoggingIn", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_message_box_network_logging_in.html", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_message_box_network_logging_in" ],
          [ "vxMessageBoxNetworkLogIn", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_message_box_network_log_in.html", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_message_box_network_log_in" ],
          [ "vxMessageBoxSaveBeforeQuit", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_message_box_save_before_quit.html", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_message_box_save_before_quit" ],
          [ "vxMessageInputBox", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_message_input_box.html", "class_vertices_engine_1_1_u_i_1_1_message_boxs_1_1vx_message_input_box" ]
        ] ],
        [ "StartupScreen", "namespace_vertices_engine_1_1_u_i_1_1_startup_screen.html", [
          [ "vxInitializationScreen", "class_vertices_engine_1_1_u_i_1_1_startup_screen_1_1vx_initialization_screen.html", "class_vertices_engine_1_1_u_i_1_1_startup_screen_1_1vx_initialization_screen" ],
          [ "vxTitleScreen", "class_vertices_engine_1_1_u_i_1_1_startup_screen_1_1vx_title_screen.html", "class_vertices_engine_1_1_u_i_1_1_startup_screen_1_1vx_title_screen" ]
        ] ],
        [ "Themes", "namespace_vertices_engine_1_1_u_i_1_1_themes.html", [
          [ "vxBaseItemTheme", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_base_item_theme.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_base_item_theme" ],
          [ "vxButtonArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_button_art_provider.html", null ],
          [ "vxComboBoxArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_combo_box_art_provider.html", null ],
          [ "vxDialogArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_dialog_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_dialog_art_provider" ],
          [ "vxFileDialoglItemArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_file_dialogl_item_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_file_dialogl_item_art_provider" ],
          [ "vxFileExplorerItemArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_file_explorer_item_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_file_explorer_item_art_provider" ],
          [ "vxLoadingScreenTheme", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_loading_screen_theme.html", null ],
          [ "vxMenuItemArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_menu_item_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_menu_item_art_provider" ],
          [ "vxMenuScreenArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_menu_screen_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_menu_screen_art_provider" ],
          [ "vxMenuTheme", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_menu_theme.html", null ],
          [ "vxMessageBoxArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_message_box_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_message_box_art_provider" ],
          [ "vxModDialoglItemArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_mod_dialogl_item_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_mod_dialogl_item_art_provider" ],
          [ "vxScrollBarArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_scroll_bar_art_provider.html", null ],
          [ "vxScrollPanelArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_scroll_panel_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_scroll_panel_art_provider" ],
          [ "vxScrollPanelItemArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_scroll_panel_item_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_scroll_panel_item_art_provider" ],
          [ "vxSliderArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_slider_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_slider_art_provider" ],
          [ "vxSpinnerControlArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_spinner_control_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_spinner_control_art_provider" ],
          [ "vxTabPageTabArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_tab_page_tab_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_tab_page_tab_art_provider" ],
          [ "vxTextboxArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_textbox_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_textbox_art_provider" ],
          [ "vxToolbarArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_toolbar_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_toolbar_art_provider" ],
          [ "vxToolTipArtProvider", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_tool_tip_art_provider.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_tool_tip_art_provider" ],
          [ "vxUITheme", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_u_i_theme.html", "class_vertices_engine_1_1_u_i_1_1_themes_1_1vx_u_i_theme" ]
        ] ],
        [ "IGuiArtProvider", "interface_vertices_engine_1_1_u_i_1_1_i_gui_art_provider.html", "interface_vertices_engine_1_1_u_i_1_1_i_gui_art_provider" ],
        [ "vxArtProviderBase", "class_vertices_engine_1_1_u_i_1_1vx_art_provider_base.html", "class_vertices_engine_1_1_u_i_1_1vx_art_provider_base" ],
        [ "vxColourTheme", "class_vertices_engine_1_1_u_i_1_1vx_colour_theme.html", "class_vertices_engine_1_1_u_i_1_1vx_colour_theme" ],
        [ "vxFontPack", "class_vertices_engine_1_1_u_i_1_1vx_font_pack.html", "class_vertices_engine_1_1_u_i_1_1vx_font_pack" ],
        [ "vxLabelArtProvider", "class_vertices_engine_1_1_u_i_1_1vx_label_art_provider.html", null ],
        [ "vxLayout", "class_vertices_engine_1_1_u_i_1_1vx_layout.html", "class_vertices_engine_1_1_u_i_1_1vx_layout" ],
        [ "vxLoadingScreenRenderer", "class_vertices_engine_1_1_u_i_1_1vx_loading_screen_renderer.html", "class_vertices_engine_1_1_u_i_1_1vx_loading_screen_renderer" ],
        [ "vxManageImportedEntitiesDialog", "class_vertices_engine_1_1_u_i_1_1vx_manage_imported_entities_dialog.html", "class_vertices_engine_1_1_u_i_1_1vx_manage_imported_entities_dialog" ],
        [ "vxSceneExportDialog", "class_vertices_engine_1_1_u_i_1_1vx_scene_export_dialog.html", "class_vertices_engine_1_1_u_i_1_1vx_scene_export_dialog" ],
        [ "vxSignInBusyScreen", "class_vertices_engine_1_1_u_i_1_1vx_sign_in_busy_screen.html", "class_vertices_engine_1_1_u_i_1_1vx_sign_in_busy_screen" ],
        [ "vxUIArtProvider", "class_vertices_engine_1_1_u_i_1_1vx_u_i_art_provider.html", "class_vertices_engine_1_1_u_i_1_1vx_u_i_art_provider" ],
        [ "vxUIControl", "class_vertices_engine_1_1_u_i_1_1vx_u_i_control.html", "class_vertices_engine_1_1_u_i_1_1vx_u_i_control" ],
        [ "vxUIControlTheme", "class_vertices_engine_1_1_u_i_1_1vx_u_i_control_theme.html", "class_vertices_engine_1_1_u_i_1_1vx_u_i_control_theme" ],
        [ "vxUIManager", "class_vertices_engine_1_1_u_i_1_1vx_u_i_manager.html", "class_vertices_engine_1_1_u_i_1_1vx_u_i_manager" ]
      ] ],
      [ "Util", "namespace_vertices_engine_1_1_util.html", [
        [ "ISnapbox", "interface_vertices_engine_1_1_util_1_1_i_snapbox.html", null ],
        [ "vxSnapBox", "class_vertices_engine_1_1_util_1_1vx_snap_box.html", "class_vertices_engine_1_1_util_1_1vx_snap_box" ]
      ] ],
      [ "Utilities", "namespace_vertices_engine_1_1_utilities.html", [
        [ "NativeMessageBox", "class_vertices_engine_1_1_utilities_1_1_native_message_box.html", null ],
        [ "SteppedVar", "class_vertices_engine_1_1_utilities_1_1_stepped_var.html", null ],
        [ "vxColourUtil", "class_vertices_engine_1_1_utilities_1_1vx_colour_util.html", "class_vertices_engine_1_1_utilities_1_1vx_colour_util" ],
        [ "vxGeometryHelper", "class_vertices_engine_1_1_utilities_1_1vx_geometry_helper.html", "class_vertices_engine_1_1_utilities_1_1vx_geometry_helper" ],
        [ "vxIO", "class_vertices_engine_1_1_utilities_1_1vx_i_o.html", "class_vertices_engine_1_1_utilities_1_1vx_i_o" ],
        [ "vxPlatformString", "class_vertices_engine_1_1_utilities_1_1vx_platform_string.html", "class_vertices_engine_1_1_utilities_1_1vx_platform_string" ],
        [ "vxSystemInfo", "class_vertices_engine_1_1_utilities_1_1vx_system_info.html", null ],
        [ "vxUtil", "class_vertices_engine_1_1_utilities_1_1vx_util.html", "class_vertices_engine_1_1_utilities_1_1vx_util" ]
      ] ],
      [ "Workshop", "namespace_vertices_engine_1_1_workshop.html", [
        [ "Events", "namespace_vertices_engine_1_1_workshop_1_1_events.html", [
          [ "vxWorkshopItemOpenEventArgs", "class_vertices_engine_1_1_workshop_1_1_events_1_1vx_workshop_item_open_event_args.html", "class_vertices_engine_1_1_workshop_1_1_events_1_1vx_workshop_item_open_event_args" ],
          [ "vxWorkshopItemPublishedEventArgs", "class_vertices_engine_1_1_workshop_1_1_events_1_1vx_workshop_item_published_event_args.html", "class_vertices_engine_1_1_workshop_1_1_events_1_1vx_workshop_item_published_event_args" ],
          [ "vxWorkshopSeachReceievedEventArgs", "class_vertices_engine_1_1_workshop_1_1_events_1_1vx_workshop_seach_receieved_event_args.html", "class_vertices_engine_1_1_workshop_1_1_events_1_1vx_workshop_seach_receieved_event_args" ]
        ] ],
        [ "Providers", "namespace_vertices_engine_1_1_workshop_1_1_providers.html", [
          [ "Generic", "namespace_vertices_engine_1_1_workshop_1_1_providers_1_1_generic.html", [
            [ "vxGenericWorkshopWrapper", "class_vertices_engine_1_1_workshop_1_1_providers_1_1_generic_1_1vx_generic_workshop_wrapper.html", "class_vertices_engine_1_1_workshop_1_1_providers_1_1_generic_1_1vx_generic_workshop_wrapper" ]
          ] ]
        ] ],
        [ "UI", "namespace_vertices_engine_1_1_workshop_1_1_u_i.html", [
          [ "vxWorkshopDialogItem", "class_vertices_engine_1_1_workshop_1_1_u_i_1_1vx_workshop_dialog_item.html", "class_vertices_engine_1_1_workshop_1_1_u_i_1_1vx_workshop_dialog_item" ],
          [ "vxWorkshopDialogItemArtProvider", "class_vertices_engine_1_1_workshop_1_1_u_i_1_1vx_workshop_dialog_item_art_provider.html", null ],
          [ "vxWorkshopSearchBusyScreen", "class_vertices_engine_1_1_workshop_1_1_u_i_1_1vx_workshop_search_busy_screen.html", "class_vertices_engine_1_1_workshop_1_1_u_i_1_1vx_workshop_search_busy_screen" ],
          [ "vxWorkshopSearchResultDialog", "class_vertices_engine_1_1_workshop_1_1_u_i_1_1vx_workshop_search_result_dialog.html", "class_vertices_engine_1_1_workshop_1_1_u_i_1_1vx_workshop_search_result_dialog" ]
        ] ],
        [ "vxIWorkshopItem", "interface_vertices_engine_1_1_workshop_1_1vx_i_workshop_item.html", null ],
        [ "vxIWorkshopWrapper", "interface_vertices_engine_1_1_workshop_1_1vx_i_workshop_wrapper.html", "interface_vertices_engine_1_1_workshop_1_1vx_i_workshop_wrapper" ],
        [ "vxWorkshop", "class_vertices_engine_1_1_workshop_1_1vx_workshop.html", null ],
        [ "vxWorkshopSearchQuery", "class_vertices_engine_1_1_workshop_1_1vx_workshop_search_query.html", "class_vertices_engine_1_1_workshop_1_1vx_workshop_search_query" ],
        [ "vxWorkshopSearchResults", "class_vertices_engine_1_1_workshop_1_1vx_workshop_search_results.html", "class_vertices_engine_1_1_workshop_1_1vx_workshop_search_results" ],
        [ "vxWorkshopUploadDialog", "class_vertices_engine_1_1_workshop_1_1vx_workshop_upload_dialog.html", "class_vertices_engine_1_1_workshop_1_1vx_workshop_upload_dialog" ],
        [ "vxWorkshopUploadWorker", "class_vertices_engine_1_1_workshop_1_1vx_workshop_upload_worker.html", "class_vertices_engine_1_1_workshop_1_1vx_workshop_upload_worker" ],
        [ "WorkshopItemUploadResult", "struct_vertices_engine_1_1_workshop_1_1_workshop_item_upload_result.html", "struct_vertices_engine_1_1_workshop_1_1_workshop_item_upload_result" ]
      ] ],
      [ "ImportedFileInfo", "struct_vertices_engine_1_1_imported_file_info.html", null ],
      [ "RenderPassTransformData", "class_vertices_engine_1_1_render_pass_transform_data.html", null ],
      [ "vxAudioSettingsAttribute", "class_vertices_engine_1_1vx_audio_settings_attribute.html", "class_vertices_engine_1_1vx_audio_settings_attribute" ],
      [ "vxBaseScene", "class_vertices_engine_1_1vx_base_scene.html", "class_vertices_engine_1_1vx_base_scene" ],
      [ "vxCamera", "class_vertices_engine_1_1vx_camera.html", "class_vertices_engine_1_1vx_camera" ],
      [ "vxCamera2D", "class_vertices_engine_1_1vx_camera2_d.html", "class_vertices_engine_1_1vx_camera2_d" ],
      [ "vxCamera3D", "class_vertices_engine_1_1vx_camera3_d.html", "class_vertices_engine_1_1vx_camera3_d" ],
      [ "vxCameraChaseController", "class_vertices_engine_1_1vx_camera_chase_controller.html", "class_vertices_engine_1_1vx_camera_chase_controller" ],
      [ "vxCameraFpsController", "class_vertices_engine_1_1vx_camera_fps_controller.html", "class_vertices_engine_1_1vx_camera_fps_controller" ],
      [ "vxCameraFreeRoamController", "class_vertices_engine_1_1vx_camera_free_roam_controller.html", "class_vertices_engine_1_1vx_camera_free_roam_controller" ],
      [ "vxCameraManager", "class_vertices_engine_1_1vx_camera_manager.html", "class_vertices_engine_1_1vx_camera_manager" ],
      [ "vxCameraOrbitController", "class_vertices_engine_1_1vx_camera_orbit_controller.html", "class_vertices_engine_1_1vx_camera_orbit_controller" ],
      [ "vxCameraSceneEditorController", "class_vertices_engine_1_1vx_camera_scene_editor_controller.html", "class_vertices_engine_1_1vx_camera_scene_editor_controller" ],
      [ "vxComponent", "class_vertices_engine_1_1vx_component.html", "class_vertices_engine_1_1vx_component" ],
      [ "vxConsole", "class_vertices_engine_1_1vx_console.html", "class_vertices_engine_1_1vx_console" ],
      [ "vxCoroutine", "class_vertices_engine_1_1vx_coroutine.html", null ],
      [ "vxCoroutineManager", "class_vertices_engine_1_1vx_coroutine_manager.html", "class_vertices_engine_1_1vx_coroutine_manager" ],
      [ "vxDebug", "class_vertices_engine_1_1vx_debug.html", "class_vertices_engine_1_1vx_debug" ],
      [ "vxDistortionEntity2D", "class_vertices_engine_1_1vx_distortion_entity2_d.html", "class_vertices_engine_1_1vx_distortion_entity2_d" ],
      [ "vxEngine", "class_vertices_engine_1_1vx_engine.html", "class_vertices_engine_1_1vx_engine" ],
      [ "vxEngineAttribute", "class_vertices_engine_1_1vx_engine_attribute.html", null ],
      [ "vxEngineSettingsAttribute", "class_vertices_engine_1_1vx_engine_settings_attribute.html", "class_vertices_engine_1_1vx_engine_settings_attribute" ],
      [ "vxEntity", "class_vertices_engine_1_1vx_entity.html", "class_vertices_engine_1_1vx_entity" ],
      [ "vxEntity2D", "class_vertices_engine_1_1vx_entity2_d.html", "class_vertices_engine_1_1vx_entity2_d" ],
      [ "vxEntity3D", "class_vertices_engine_1_1vx_entity3_d.html", "class_vertices_engine_1_1vx_entity3_d" ],
      [ "vxEntityCreationProcedure", "class_vertices_engine_1_1vx_entity_creation_procedure.html", null ],
      [ "vxEntityRegister", "class_vertices_engine_1_1vx_entity_register.html", "class_vertices_engine_1_1vx_entity_register" ],
      [ "vxEntitySpriteSheetDefinition", "class_vertices_engine_1_1vx_entity_sprite_sheet_definition.html", null ],
      [ "vxExtentions", "class_vertices_engine_1_1vx_extentions.html", "class_vertices_engine_1_1vx_extentions" ],
      [ "vxGame", "class_vertices_engine_1_1vx_game.html", "class_vertices_engine_1_1vx_game" ],
      [ "vxGameAttributeException", "class_vertices_engine_1_1vx_game_attribute_exception.html", "class_vertices_engine_1_1vx_game_attribute_exception" ],
      [ "vxGameConfig", "class_vertices_engine_1_1vx_game_config.html", null ],
      [ "vxGameConfigurationsAttribute", "class_vertices_engine_1_1vx_game_configurations_attribute.html", "class_vertices_engine_1_1vx_game_configurations_attribute" ],
      [ "vxGameObject", "class_vertices_engine_1_1vx_game_object.html", "class_vertices_engine_1_1vx_game_object" ],
      [ "vxGameplayScene2D", "class_vertices_engine_1_1vx_gameplay_scene2_d.html", "class_vertices_engine_1_1vx_gameplay_scene2_d" ],
      [ "vxGameplayScene3D", "class_vertices_engine_1_1vx_gameplay_scene3_d.html", "class_vertices_engine_1_1vx_gameplay_scene3_d" ],
      [ "vxGameplaySceneBase", "class_vertices_engine_1_1vx_gameplay_scene_base.html", "class_vertices_engine_1_1vx_gameplay_scene_base" ],
      [ "vxGameSettingsAttribute", "class_vertices_engine_1_1vx_game_settings_attribute.html", "class_vertices_engine_1_1vx_game_settings_attribute" ],
      [ "vxGraphicalSettingsAttribute", "class_vertices_engine_1_1vx_graphical_settings_attribute.html", "class_vertices_engine_1_1vx_graphical_settings_attribute" ],
      [ "vxIEngineSubSystem", "interface_vertices_engine_1_1vx_i_engine_sub_system.html", null ],
      [ "vxIInitializationStep", "interface_vertices_engine_1_1vx_i_initialization_step.html", null ],
      [ "vxInputSettingsAttribute", "class_vertices_engine_1_1vx_input_settings_attribute.html", "class_vertices_engine_1_1vx_input_settings_attribute" ],
      [ "vxInternalAssets", "class_vertices_engine_1_1vx_internal_assets.html", "class_vertices_engine_1_1vx_internal_assets" ],
      [ "vxISceneSubSystem", "interface_vertices_engine_1_1vx_i_scene_sub_system.html", null ],
      [ "vxISelectable", "interface_vertices_engine_1_1vx_i_selectable.html", null ],
      [ "vxISubSystem", "interface_vertices_engine_1_1vx_i_sub_system.html", "interface_vertices_engine_1_1vx_i_sub_system" ],
      [ "vxItemList", "class_vertices_engine_1_1vx_item_list.html", "class_vertices_engine_1_1vx_item_list" ],
      [ "vxLocalizer", "class_vertices_engine_1_1vx_localizer.html", "class_vertices_engine_1_1vx_localizer" ],
      [ "vxLocKeys", "class_vertices_engine_1_1vx_loc_keys.html", null ],
      [ "vxMathHelper", "class_vertices_engine_1_1vx_math_helper.html", "class_vertices_engine_1_1vx_math_helper" ],
      [ "vxRandom", "class_vertices_engine_1_1vx_random.html", "class_vertices_engine_1_1vx_random" ],
      [ "vxRangeAttribute", "class_vertices_engine_1_1vx_range_attribute.html", "class_vertices_engine_1_1vx_range_attribute" ],
      [ "vxRegisterAsSandboxEntityAttribute", "class_vertices_engine_1_1vx_register_as_sandbox_entity_attribute.html", "class_vertices_engine_1_1vx_register_as_sandbox_entity_attribute" ],
      [ "vxSandboxEntityCategory", "class_vertices_engine_1_1vx_sandbox_entity_category.html", null ],
      [ "vxSandboxEntityMetaAttribute", "class_vertices_engine_1_1vx_sandbox_entity_meta_attribute.html", null ],
      [ "vxSandboxEntityRegistrationInfo", "class_vertices_engine_1_1vx_sandbox_entity_registration_info.html", "class_vertices_engine_1_1vx_sandbox_entity_registration_info" ],
      [ "vxSandboxEntitySubCategory", "class_vertices_engine_1_1vx_sandbox_entity_sub_category.html", "class_vertices_engine_1_1vx_sandbox_entity_sub_category" ],
      [ "vxSandboxFileLoadResult", "class_vertices_engine_1_1vx_sandbox_file_load_result.html", null ],
      [ "vxSandboxItemSelectedEventArgs", "class_vertices_engine_1_1vx_sandbox_item_selected_event_args.html", "class_vertices_engine_1_1vx_sandbox_item_selected_event_args" ],
      [ "vxSandboxItemSelectedForInspectorEventArgs", "class_vertices_engine_1_1vx_sandbox_item_selected_for_inspector_event_args.html", "class_vertices_engine_1_1vx_sandbox_item_selected_for_inspector_event_args" ],
      [ "vxSaveBusyScreen", "class_vertices_engine_1_1vx_save_busy_screen.html", "class_vertices_engine_1_1vx_save_busy_screen" ],
      [ "vxSaveBusyScreen2D", "class_vertices_engine_1_1vx_save_busy_screen2_d.html", "class_vertices_engine_1_1vx_save_busy_screen2_d" ],
      [ "vxSaveBusyScreen3D", "class_vertices_engine_1_1vx_save_busy_screen3_d.html", "class_vertices_engine_1_1vx_save_busy_screen3_d" ],
      [ "vxSceneManager", "class_vertices_engine_1_1vx_scene_manager.html", "class_vertices_engine_1_1vx_scene_manager" ],
      [ "vxSceneProperties", "class_vertices_engine_1_1vx_scene_properties.html", null ],
      [ "vxScreen", "class_vertices_engine_1_1vx_screen.html", "class_vertices_engine_1_1vx_screen" ],
      [ "vxSerialiseAttribute", "class_vertices_engine_1_1vx_serialise_attribute.html", null ],
      [ "vxSettings", "class_vertices_engine_1_1vx_settings.html", null ],
      [ "vxSettingsAttribute", "class_vertices_engine_1_1vx_settings_attribute.html", "class_vertices_engine_1_1vx_settings_attribute" ],
      [ "vxShowInInspectorAttribute", "class_vertices_engine_1_1vx_show_in_inspector_attribute.html", "class_vertices_engine_1_1vx_show_in_inspector_attribute" ],
      [ "vxTime", "class_vertices_engine_1_1vx_time.html", "class_vertices_engine_1_1vx_time" ],
      [ "vxTransform", "class_vertices_engine_1_1vx_transform.html", "class_vertices_engine_1_1vx_transform" ],
      [ "vxUtilCamera3D", "class_vertices_engine_1_1vx_util_camera3_d.html", "class_vertices_engine_1_1vx_util_camera3_d" ],
      [ "vxUtilCameraEntity", "class_vertices_engine_1_1vx_util_camera_entity.html", "class_vertices_engine_1_1vx_util_camera_entity" ],
      [ "vxWaitForSeconds", "class_vertices_engine_1_1vx_wait_for_seconds.html", null ],
      [ "vxWaterEntity", "class_vertices_engine_1_1vx_water_entity.html", "class_vertices_engine_1_1vx_water_entity" ]
    ] ],
    [ "vxExtensions", "classvx_extensions.html", "classvx_extensions" ]
];