var namespace_vertices_engine_1_1_serilization =
[
    [ "EngineInfo", "class_vertices_engine_1_1_serilization_1_1_engine_info.html", null ],
    [ "GameInfo", "class_vertices_engine_1_1_serilization_1_1_game_info.html", null ],
    [ "SandboxFileInfo", "class_vertices_engine_1_1_serilization_1_1_sandbox_file_info.html", null ],
    [ "vxFileInfo", "class_vertices_engine_1_1_serilization_1_1vx_file_info.html", null ],
    [ "vxFogState", "class_vertices_engine_1_1_serilization_1_1vx_fog_state.html", null ],
    [ "vxGraphicalAntiAliasingSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_anti_aliasing_settings.html", null ],
    [ "vxGraphicalBaseBooleanSetting", "class_vertices_engine_1_1_serilization_1_1vx_graphical_base_boolean_setting.html", "class_vertices_engine_1_1_serilization_1_1vx_graphical_base_boolean_setting" ],
    [ "vxGraphicalBaseQualitySetting", "class_vertices_engine_1_1_serilization_1_1vx_graphical_base_quality_setting.html", "class_vertices_engine_1_1_serilization_1_1vx_graphical_base_quality_setting" ],
    [ "vxGraphicalBloomSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_bloom_settings.html", null ],
    [ "vxGraphicalBlurSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_blur_settings.html", null ],
    [ "vxGraphicalDefferredLightingSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_defferred_lighting_settings.html", null ],
    [ "vxGraphicalDepthOfFieldSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_depth_of_field_settings.html", null ],
    [ "vxGraphicalEdgeDetectionSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_edge_detection_settings.html", null ],
    [ "vxGraphicalGodRaysSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_god_rays_settings.html", null ],
    [ "vxGraphicalMotionBlurSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_motion_blur_settings.html", null ],
    [ "vxGraphicalReflectionSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_reflection_settings.html", null ],
    [ "vxGraphicalShadowSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_shadow_settings.html", null ],
    [ "vxGraphicalSSAOSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_s_s_a_o_settings.html", null ],
    [ "vxGraphicalSSRSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_s_s_r_settings.html", null ],
    [ "vxGraphicalTexturesSettings", "class_vertices_engine_1_1_serilization_1_1vx_graphical_textures_settings.html", "class_vertices_engine_1_1_serilization_1_1vx_graphical_textures_settings" ],
    [ "vxSerializableColor", "class_vertices_engine_1_1_serilization_1_1vx_serializable_color.html", null ],
    [ "vxSerializableEntityState2D", "class_vertices_engine_1_1_serilization_1_1vx_serializable_entity_state2_d.html", null ],
    [ "vxSerializableEntityState3D", "class_vertices_engine_1_1_serilization_1_1vx_serializable_entity_state3_d.html", null ],
    [ "vxSerializableEnviroment", "class_vertices_engine_1_1_serilization_1_1vx_serializable_enviroment.html", null ],
    [ "vxSerializableImportedEntityInfo3D", "class_vertices_engine_1_1_serilization_1_1vx_serializable_imported_entity_info3_d.html", "class_vertices_engine_1_1_serilization_1_1vx_serializable_imported_entity_info3_d" ],
    [ "vxSerializableScene2DData", "class_vertices_engine_1_1_serilization_1_1vx_serializable_scene2_d_data.html", null ],
    [ "vxSerializableScene3DData", "class_vertices_engine_1_1_serilization_1_1vx_serializable_scene3_d_data.html", null ],
    [ "vxSerializableSceneBaseData", "class_vertices_engine_1_1_serilization_1_1vx_serializable_scene_base_data.html", null ],
    [ "vxSerializableTerrainData", "class_vertices_engine_1_1_serilization_1_1vx_serializable_terrain_data.html", null ],
    [ "vxSerializableTerrainVertex", "class_vertices_engine_1_1_serilization_1_1vx_serializable_terrain_vertex.html", null ],
    [ "vxSerializableTexture2D", "class_vertices_engine_1_1_serilization_1_1vx_serializable_texture2_d.html", null ],
    [ "vxSerializableVersion", "class_vertices_engine_1_1_serilization_1_1vx_serializable_version.html", null ],
    [ "vxSkyBoxState", "class_vertices_engine_1_1_serilization_1_1vx_sky_box_state.html", null ],
    [ "WorkshopFileInfo", "class_vertices_engine_1_1_serilization_1_1_workshop_file_info.html", null ]
];